### ISSUE TITLE
Issue with Template Wall Collision module

### ISSUE THREAD

**Issue by ravingdragoon** [kandashi/Active-Auras#205]
**Describe the bug**
Issue with CollateAuras.js when running the module with the Template Wall Collision module. This has been raised with the Template Wall Collision module as well. [Issue #6](https://github.com/EndlesNights/template-wall-collision/issues/6#issue-1109476895)

**To Reproduce**
1. Install Active Auras, Template Wall Collision, and dependencies.
2. See error in Dev Console

**Expected behavior**
No errors

**Environment:**
 - OS: Windows 10
 - Browser Chrome/Edge
 - Foundry Version V9.242
 - Module Version 0.4.02
 - All Modules Disabled: Yes

**Additional context**
Error in Dev Console:
```
aura.js:176 
 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at Function.UpdateToken (aura.js:176:36)
    at Function.UpdateAllTokens (aura.js:111:25)
    at Function.MainAura (aura.js:42:27)
    at CollateAuras (collateAuras.js:65:21)
UpdateToken	@	aura.js:176
UpdateAllTokens	@	aura.js:111
MainAura	@	aura.js:42
CollateAuras	@	collateAuras.js:65
await in CollateAuras (async)		
(anonymous)	@	AAhooks.js:22
_call	@	foundry.js:294
callAll	@	foundry.js:253
setupGame	@	foundry.js:5547
```

**Comment by kandashi** [comment]
I dont see how anything here relates to the Wall Collision module? 

It either means it cannot find the correct token to measure against, or the source of the aura

**Comment by ravingdragoon** [comment]
I don't know the cause, but if I turn off the Wall Collision module I do not get the error.
