### ISSUE TITLE
Undefined ID

### ISSUE THREAD

**Issue by Dyrnwyrm** [kandashi/Active-Auras#285]
**Describe the bug**
Got this error on console.....

undefined aura does not exist on the embedded collection
**To Reproduce**
1. Add an active aura
2. Add the effects
3.Check if enable
4. Canvas an console error
**Expected behavior**
Aura just applying once, not stacking

**Screenshots**

![Captura](https://github.com/kandashi/Active-Auras/assets/129613553/f1621448-c620-4916-96d2-d33d1af0a72c)

**Environment:**
 - OS: windows 10
 - Browser Foundry Client
 - Foundry Version 11.305
 - Module Version 0.7.2
 - All Modules Disabled: No
 - Module List if no: 
MidiQol
ActiveAuras
ChrisPremades (and dependencies)
Times-Up
Simple Calendar

**Additional context**
The aura keeps adding itself to actors it seems like the effect is unable to delete itself, i deleted the first one but the new feature has the same issue
![image](https://github.com/kandashi/Active-Auras/assets/129613553/be2a867a-5c4b-49b3-b350-cccf92093d24)
![image](https://github.com/kandashi/Active-Auras/assets/129613553/1adf2673-c6f7-45dd-8cf8-7273462f2d16)

**Comment by MrPrimate** [comment]
Does it work with just DAE and Active Auras enabled? Can you share the details tab of the item this originates from.

**Comment by mrguenther** [comment]
I've found that I can reproduce this by selecting N (>=2) tokens for the same character, all of them linked to the canonical actor data, and moving them into or out of an aura. If they all enter the aura in the same motion, the module adds N copies of the `ActiveEffect` to the actor. If any of them leave the aura, the module tries to delete each `ActiveEffect` N times, causing errors on all but the first deletion attempts.

This is admittedly an odd situation, but I've also found that Token Attacher makes these sorts of errors vastly more common in other situations.

Here's an example of me moving two identical, linked tokens into and back out of an aura:
```
FoundryVTT | 2024-07-31 03:15:56 | [info] Created ActiveEffect with id [EBS6nxNqCcbmApEs] in parent Actor [FqBWU01GjvkdzPvs]
FoundryVTT | 2024-07-31 03:15:56 | [info] Created ActiveEffect with id [lWeQa99ga1dh7ne2] in parent Actor [FqBWU01GjvkdzPvs]
FoundryVTT | 2024-07-31 03:15:57 | [info] Deleted ActiveEffect with id [EBS6nxNqCcbmApEs] in parent Actor [FqBWU01GjvkdzPvs]
FoundryVTT | 2024-07-31 03:15:57 | [error] ActiveEffect "EBS6nxNqCcbmApEs" does not exist!
Error: ActiveEffect "EBS6nxNqCcbmApEs" does not exist!
    at file:///home/mrguenther/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:6671
    at Array.map (<anonymous>)
    at ServerDatabaseBackend._deleteDocuments (file:///home/mrguenther/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:6641)
    at ServerDatabaseBackend.delete (file:///home/mrguenther/foundryvtt/resources/app/common/abstract/backend.mjs:174:17)
    at async Semaphore._try (file:///home/mrguenther/foundryvtt/resources/app/common/utils/semaphore.mjs:101:17)
FoundryVTT | 2024-07-31 03:15:57 | [info] Deleted ActiveEffect with id [lWeQa99ga1dh7ne2] in parent Actor [FqBWU01GjvkdzPvs]
FoundryVTT | 2024-07-31 03:15:57 | [error] ActiveEffect "lWeQa99ga1dh7ne2" does not exist!
Error: ActiveEffect "lWeQa99ga1dh7ne2" does not exist!
    at file:///home/mrguenther/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:6671
    at Array.map (<anonymous>)
    at ServerDatabaseBackend._deleteDocuments (file:///home/mrguenther/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:6641)
    at ServerDatabaseBackend.delete (file:///home/mrguenther/foundryvtt/resources/app/common/abstract/backend.mjs:174:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Semaphore._try (file:///home/mrguenther/foundryvtt/resources/app/common/utils/semaphore.mjs:101:17)
```

**Comment by MrPrimate** [comment]
> I've found that I can reproduce this by selecting N (>=2) tokens for the same character, all of them linked to the canonical actor data, and moving them into or out of an aura. If they all enter the aura in the same motion, the module adds N copies of the `ActiveEffect` to the actor. If any of them leave the aura, the module tries to delete each `ActiveEffect` N times, causing errors on all but the first deletion attempt.
> 
> Having two tokens for the same unique character is admittedly an odd situation, but I've also found that the popular Token Attacher module makes these issues vastly more common in all sorts of situations.
> 
> Here's an example of me moving two identical tokens, both linked to the same actor data, into and back out of an aura:
> 
> ```
> FoundryVTT | 2024-07-31 03:15:56 | [info] Created ActiveEffect with id [EBS6nxNqCcbmApEs] in parent Actor [FqBWU01GjvkdzPvs]
> FoundryVTT | 2024-07-31 03:15:56 | [info] Created ActiveEffect with id [lWeQa99ga1dh7ne2] in parent Actor [FqBWU01GjvkdzPvs]
> FoundryVTT | 2024-07-31 03:15:57 | [info] Deleted ActiveEffect with id [EBS6nxNqCcbmApEs] in parent Actor [FqBWU01GjvkdzPvs]
> FoundryVTT | 2024-07-31 03:15:57 | [error] ActiveEffect "EBS6nxNqCcbmApEs" does not exist!
> Error: ActiveEffect "EBS6nxNqCcbmApEs" does not exist!
>     at file:///home/mrguenther/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:6671
>     at Array.map (<anonymous>)
>     at ServerDatabaseBackend._deleteDocuments (file:///home/mrguenther/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:6641)
>     at ServerDatabaseBackend.delete (file:///home/mrguenther/foundryvtt/resources/app/common/abstract/backend.mjs:174:17)
>     at async Semaphore._try (file:///home/mrguenther/foundryvtt/resources/app/common/utils/semaphore.mjs:101:17)
> FoundryVTT | 2024-07-31 03:15:57 | [info] Deleted ActiveEffect with id [lWeQa99ga1dh7ne2] in parent Actor [FqBWU01GjvkdzPvs]
> FoundryVTT | 2024-07-31 03:15:57 | [error] ActiveEffect "lWeQa99ga1dh7ne2" does not exist!
> Error: ActiveEffect "lWeQa99ga1dh7ne2" does not exist!
>     at file:///home/mrguenther/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:6671
>     at Array.map (<anonymous>)
>     at ServerDatabaseBackend._deleteDocuments (file:///home/mrguenther/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:6641)
>     at ServerDatabaseBackend.delete (file:///home/mrguenther/foundryvtt/resources/app/common/abstract/backend.mjs:174:17)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Semaphore._try (file:///home/mrguenther/foundryvtt/resources/app/common/utils/semaphore.mjs:101:17)
> ```


I don't think there is a way I can easily handle this, as each token is supposed to have its own set of actor data that it can use, which isn't the case when both tokens are linked to the same actor.

**Comment by mrguenther** [comment]
What about confirming that the effect with that ID hasn't already been
added/removed before adding/removing it?

Anyway, the bigger issue is when combined with the Token Attacher module.
In that case, they don't have to be duplicate tokens linked to the same
actor. I often end up with like 100 error messages after I move a complex
vehicle made using Token Attacher. You can reproduce the error with just
two attached tokens, though. Given how incredibly popular that module is,
I'd consider this to be a fairly important issue.

**Comment by mrguenther** [comment]
It looks like the issue often happens when dragging multiple tokens through a wall, such that the effect is rapidly removed and re-applied. I think there's a race condition.

**Comment by MrPrimate** [comment]
I have made some improvements in v0.11.0 which should help address some of these
