### ISSUE TITLE
ERROR CAUGHT in RemoveActiveEffects Error: Undefined id does not exist in embeddedCollection collection

### ISSUE THREAD

**Issue by mvanduijvenvoorde** [kandashi/Active-Auras#319]
**Describe the bug**
At FoundryVTT startup I get the following errors. One of my players is a Paladin and has 2 active auras.

**To Reproduce**
Startup FoundryVTT
![active_auras_error](https://github.com/kandashi/Active-Auras/assets/70683364/69bcf758-d766-4b6a-8256-9b32b1bc0004)

**Expected behavior**
No error on startup FoundryVTT

**Screenshots**
See attachment

**Environment:**
 - OS: Windows
 - Browser Chrome
 - Foundry Version 11
 - Module Version Apr 3
 - All Modules Disabled: No
 - Module List if no: 

**Additional context**
gger.mjs:62 ActiveAuras | ERR > ERROR CAUGHT in RemoveActiveEffects Error: undefined id [pXshtCP0CtcsKXOJ] does not exist in the EmbeddedCollection collection.
    at EmbeddedCollection.get (/E:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/embedded-collection.mjs:164:36)
    at /E:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:5212
    at Array.map (<anonymous>)
    at ServerDatabaseBackend._deleteDocuments (/E:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:5202)
    at ServerDatabaseBackend.delete (/E:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/backend.mjs:182:17)
    at async Semaphore._try (/E:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)
l

**Comment by mvanduijvenvoorde** [comment]
Link with Undefined ID #285  ?

**Comment by MrPrimate** [comment]
I'm going to need more details on how to reliably replicate this, and with only the one or two modules needed for those aura effects.

**Comment by mrguenther** [comment]
I added some reproduction information to #285.

**Comment by MrPrimate** [comment]
I have made some improvements in v0.11.0 which should resolve this.
